name: Generate Draft Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create for the release'
        required: true

jobs:
  release:
    permissions:
      contents: write

    runs-on: windows-latest
    name: Generate Release
    env:
      TAG: ${{ github.event.inputs.tag }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          8.0.x

    - name: Build
      shell: bash
      run: bash ./build.sh

    - name: Create version file
      env:
        TAG: ${{ github.event.inputs.tag }}
      run: $env:TAG | Out-File -FilePath build/version.txt -NoNewline

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.inputs.tag }}
      run: |
        # Aggregate zipped files into an array in powershell & version.txt, only keep the relative path
        $files = Get-ChildItem -Path build -Recurse -Include *.zip,version.txt | ForEach-Object { $_.FullName -replace [regex]::Escape((Get-Location).Path + '\'), '' }

        Write-Host "Found $($files.Count) files to upload"
        Write-Host "Creating draft release for $env:TAG"

        gh release create -d -t "Wireless Kit Addon $env:TAG" "$env:TAG" $files -F ./build/hashes.txt
