name: Generate Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create for the release'
        required: true

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    name: Generate Release
    env:
      TAG: ${{ github.event.inputs.tag }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          8.0.x

    - name: Build
      run: bash ./build.sh

    - name: Create version file
      run: echo "$TAG" > build/version.txt

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        declare -a files
        
        # Add version file
        files+=("build/version.txt")

        # Add the plugin zip files
        files+=("build/plugin/0.5.x/WirelessKitAddon-0.5.x.zip")
        files+=("build/plugin/0.6.x/WirelessKitAddon-0.6.x.zip")

        # Add all ux zip files
        for file in build/ux/*.zip; do
          files+=("$file")
        done

        gh release create -d -t "Wireless Kit Addon $TAG" "$TAG" "${files[@]}" -F build/hashes.txt