name: Build UX

on:
  push:
    paths:
      - 'WirelessKitAddon.Lib/**'
      - 'WirelessKitAddon.UX/**'
      - 'WirelessKitAddon.UX.Desktop/**'
      - 'WirelessKitAddon.UX.Windows/**'
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  Build:

    strategy:
      matrix:
        runtime: [win-x64, win-x86, win-arm64, linux-x64, linux-arm64, linux-arm, osx-x64, osx-arm64]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Build
      env:
        platform: ${{ matrix.runtime }}
      run: bash ./build-single-ux.sh $platform

    - name: Remove PDB files
      run: |
        find ./build/ux -name "*.pdb" -type f -delete

    - name: Generate artifact name
      env:
        platform: ${{ matrix.runtime }}
      run: echo "artifact_name=WirelessKitAddon.UX-${{ matrix.runtime }}" >> $GITHUB_ENV

    - uses: actions/upload-artifact@main
      name: Upload artifact
      with:
        name: ${{ env.artifact_name }}
        path: build/ux/${{ matrix.runtime }}